services:
  # backend:
  #   build: ./backend
  #   container_name: dic_backend
  #   ports:
  #   - "8080:8080"
  #   environment:
  #   - NODE_ENV=production
  #   volumes:
  #   - ./backend/flags:/flags:ro
  #   networks:
  #   - dicnet
  orion_front:
    build: ./orion
    container_name: orion_front
    expose:
    - "3000"

  orion_mail:
    build: ./orion-mail
    expose:
      - "80"
    environment:
      - ROUNDCUBE_DEFAULT_HOST=localhost
      - ROUNDCUBE_DB_TYPE=mysql
      - ROUNDCUBE_DB_HOST=roundcube-db
      - ROUNDCUBE_DB_USER=roundcube
      - ROUNDCUBE_DB_PASSWORD=roundcubepass
      - ROUNDCUBE_DB_NAME=roundcube
  roundcube-db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: roundcube
      MYSQL_USER: roundcube
      MYSQL_PASSWORD: roundcubepass
    volumes:
      - ./roundcube-data:/var/lib/mysql
  nginx:
    image: nginx:alpine
    container_name: orion_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - orion_front

